version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Share-e-care-Nodejs
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/app_build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ec2-user
